# -*- coding: utf-8 -*-
"""fish_split.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bbF3YkWRpGr3-SpfgMAyjg0VLuiLvFdK
"""

import os
d = '.'
subdirs = [os.path.join(d, o) for o in os.listdir(d) if os.path.isdir(os.path.join(d,o))]
print(subdirs)

#Run to make 9 folders in all 3 types: Train, Test, Val

f_names=[temp[2:] for temp in subdirs[1:]]
print(f_names)
target_folder='./test'
for foldername in f_names:
    try:
        os.mkdir(os.path.join(target_folder, foldername))
    except WindowsError:
        # Handle the case where the target dir already exist.
        print("excepttt")
        pass

print(subdirs[1:])

import math
s_n=["{0:03}".format(i) for i in range(1,200)]
final_subdirs=[]
dummy_subdir=subdirs
for x in subdirs[1:]:
    base=x[2:]
    subdirs = [os.path.join(base, o) for o in os.listdir(base) if os.path.isdir(os.path.join(base,o))]
    #print(subdirs)
    final_subdirs.append(subdirs[0])

print(final_subdirs)


sub_subdir=dummy_subdir[1:9]
print(sub_subdir)

import math
s_n=["{0:04}".format(i) for i in range(1,1001)]
total=0
temp=1
for dirnames in final_subdirs[1:8]:
    files=os.listdir(dirnames)
    total_files=len(files)
    train_files= math.floor(( len(files)*7 )/10)
    val_files= math.floor(( len(files)*1 )/10)
    test_files= total_files - train_files - val_files
    print("Directory : ",dirnames," Total : ",total_files," Train : ",train_files," Val : ",val_files," Test : ",test_files)
    
    for i in range(0,train_files):
        os.rename("./"+dirnames+"/"+files[i],"./train/"+sub_subdir[temp]+"/"+s_n[i]+".jpg")
        
    for j in range(train_files,train_files+val_files):
        os.rename("./"+dirnames+"/"+files[j],"./val/"+sub_subdir[temp]+"/"+s_n[j]+".jpg")
        
    for k in range(train_files+val_files,train_files+val_files+test_files):
        os.rename("./"+dirnames+"/"+files[k],"./test/"+sub_subdir[temp]+"/"+s_n[k]+".jpg")
    
    temp+=1

import math
s_n=["{0:04}".format(i) for i in range(1,1000)]
total=0
for dirnames in subdirs[1:]:
    files=os.listdir(dirnames)
    total_files=len(files)
    train_files= math.floor(( len(files)*7 )/10)
    val_files= math.floor(( len(files)*1 )/10)
    test_files= total_files - train_files - val_files
    print("Directory : ",dirnames," Total : ",total_files," Train : ",train_files," Val : ",val_files," Test : ",test_files)
    
    
    for i in range(0,train_files):
        os.rename(dirnames+"/"+files[i],"./train/"+dirnames[2:]+"/"+s_n[i]+".jpg")
        
    for j in range(train_files,train_files+val_files):
        os.rename(dirnames+"/"+files[j],"./val/"+dirnames[2:]+"/"+s_n[j]+".jpg")
        
    for k in range(train_files+val_files,train_files+val_files+test_files):
        os.rename(dirnames+"/"+files[k],"./test/"+dirnames[2:]+"/"+s_n[k]+".jpg")

